/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4-dev */

#ifndef PB_VECTOR_TILE_VECTOR_TILE_PB_H_INCLUDED
#define PB_VECTOR_TILE_VECTOR_TILE_PB_H_INCLUDED
#include <maply_pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _vector_tile_Tile_GeomType {
    vector_tile_Tile_GeomType_UNKNOWN = 0,
    vector_tile_Tile_GeomType_POINT = 1,
    vector_tile_Tile_GeomType_LINESTRING = 2,
    vector_tile_Tile_GeomType_POLYGON = 3
} vector_tile_Tile_GeomType;

/* Struct definitions */
typedef struct _vector_tile_Tile {
    pb_callback_t layers;
    pb_extension_t *extensions;
} vector_tile_Tile;

typedef struct _vector_tile_Tile_Feature {
    bool has_id;
    uint64_t id;
    pb_callback_t tags;
    bool has_type;
    vector_tile_Tile_GeomType type;
    pb_callback_t geometry;
} vector_tile_Tile_Feature;

typedef struct _vector_tile_Tile_Layer {
    pb_callback_t name;
    pb_callback_t features;
    pb_callback_t keys;
    pb_callback_t values;
    bool has_extent;
    uint32_t extent;
    uint32_t version;
    pb_extension_t *extensions;
} vector_tile_Tile_Layer;

typedef struct _vector_tile_Tile_Value {
    pb_callback_t string_value;
    bool has_float_value;
    float float_value;
    bool has_double_value;
    double double_value;
    bool has_int_value;
    int64_t int_value;
    bool has_uint_value;
    uint64_t uint_value;
    bool has_sint_value;
    int64_t sint_value;
    bool has_bool_value;
    bool bool_value;
    pb_extension_t *extensions;
} vector_tile_Tile_Value;


/* Helper constants for enums */
#define _vector_tile_Tile_GeomType_MIN vector_tile_Tile_GeomType_UNKNOWN
#define _vector_tile_Tile_GeomType_MAX vector_tile_Tile_GeomType_POLYGON
#define _vector_tile_Tile_GeomType_ARRAYSIZE ((vector_tile_Tile_GeomType)(vector_tile_Tile_GeomType_POLYGON+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define vector_tile_Tile_init_default            {{{NULL}, NULL}, NULL}
#define vector_tile_Tile_Value_init_default      {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL}
#define vector_tile_Tile_Feature_init_default    {false, 0ull, {{NULL}, NULL}, false, vector_tile_Tile_GeomType_UNKNOWN, {{NULL}, NULL}}
#define vector_tile_Tile_Layer_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 4096u, 1u, NULL}
#define vector_tile_Tile_init_zero               {{{NULL}, NULL}, NULL}
#define vector_tile_Tile_Value_init_zero         {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, NULL}
#define vector_tile_Tile_Feature_init_zero       {false, 0, {{NULL}, NULL}, false, _vector_tile_Tile_GeomType_MIN, {{NULL}, NULL}}
#define vector_tile_Tile_Layer_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, 0, NULL}

/* Field tags (for use in manual encoding/decoding) */
#define vector_tile_Tile_layers_tag              3
#define vector_tile_Tile_Feature_id_tag          1
#define vector_tile_Tile_Feature_tags_tag        2
#define vector_tile_Tile_Feature_type_tag        3
#define vector_tile_Tile_Feature_geometry_tag    4
#define vector_tile_Tile_Layer_name_tag          1
#define vector_tile_Tile_Layer_features_tag      2
#define vector_tile_Tile_Layer_keys_tag          3
#define vector_tile_Tile_Layer_values_tag        4
#define vector_tile_Tile_Layer_extent_tag        5
#define vector_tile_Tile_Layer_version_tag       15
#define vector_tile_Tile_Value_string_value_tag  1
#define vector_tile_Tile_Value_float_value_tag   2
#define vector_tile_Tile_Value_double_value_tag  3
#define vector_tile_Tile_Value_int_value_tag     4
#define vector_tile_Tile_Value_uint_value_tag    5
#define vector_tile_Tile_Value_sint_value_tag    6
#define vector_tile_Tile_Value_bool_value_tag    7

/* Struct field encoding specification for nanopb */
#define vector_tile_Tile_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  layers,            3) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,       16)
#define vector_tile_Tile_CALLBACK pb_default_field_callback
#define vector_tile_Tile_DEFAULT NULL
#define vector_tile_Tile_layers_MSGTYPE vector_tile_Tile_Layer

#define vector_tile_Tile_Value_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   string_value,      1) \
X(a, STATIC,   OPTIONAL, FLOAT,    float_value,       2) \
X(a, STATIC,   OPTIONAL, DOUBLE,   double_value,      3) \
X(a, STATIC,   OPTIONAL, INT64,    int_value,         4) \
X(a, STATIC,   OPTIONAL, UINT64,   uint_value,        5) \
X(a, STATIC,   OPTIONAL, SINT64,   sint_value,        6) \
X(a, STATIC,   OPTIONAL, BOOL,     bool_value,        7) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,        8)
#define vector_tile_Tile_Value_CALLBACK pb_default_field_callback
#define vector_tile_Tile_Value_DEFAULT NULL

#define vector_tile_Tile_Feature_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   id,                1) \
X(a, CALLBACK, REPEATED, UINT32,   tags,              2) \
X(a, STATIC,   OPTIONAL, UENUM,    type,              3) \
X(a, CALLBACK, REPEATED, UINT32,   geometry,          4)
#define vector_tile_Tile_Feature_CALLBACK pb_default_field_callback
#define vector_tile_Tile_Feature_DEFAULT (const pb_byte_t*)"\x08\x00\x00"

#define vector_tile_Tile_Layer_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   name,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  features,          2) \
X(a, CALLBACK, REPEATED, STRING,   keys,              3) \
X(a, CALLBACK, REPEATED, MESSAGE,  values,            4) \
X(a, STATIC,   OPTIONAL, UINT32,   extent,            5) \
X(a, STATIC,   REQUIRED, UINT32,   version,          15) \
X(a, CALLBACK, OPTIONAL, EXTENSION, extensions,       16)
#define vector_tile_Tile_Layer_CALLBACK pb_default_field_callback
#define vector_tile_Tile_Layer_DEFAULT (const pb_byte_t*)"\x28\x80\x20\x78\x01\x00"
#define vector_tile_Tile_Layer_features_MSGTYPE vector_tile_Tile_Feature
#define vector_tile_Tile_Layer_values_MSGTYPE vector_tile_Tile_Value

extern const pb_msgdesc_t vector_tile_Tile_msg;
extern const pb_msgdesc_t vector_tile_Tile_Value_msg;
extern const pb_msgdesc_t vector_tile_Tile_Feature_msg;
extern const pb_msgdesc_t vector_tile_Tile_Layer_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vector_tile_Tile_fields &vector_tile_Tile_msg
#define vector_tile_Tile_Value_fields &vector_tile_Tile_Value_msg
#define vector_tile_Tile_Feature_fields &vector_tile_Tile_Feature_msg
#define vector_tile_Tile_Layer_fields &vector_tile_Tile_Layer_msg

/* Maximum encoded size of messages (where known) */
/* vector_tile_Tile_size depends on runtime parameters */
/* vector_tile_Tile_Value_size depends on runtime parameters */
/* vector_tile_Tile_Feature_size depends on runtime parameters */
/* vector_tile_Tile_Layer_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
