/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_Matrix4d */

#ifndef _Included_com_mousebirdconsulting_maply_Matrix4d
#define _Included_com_mousebirdconsulting_maply_Matrix4d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_Matrix4d
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_Matrix4d_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_Matrix4d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_Matrix4d_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
