/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_ViewState */

#ifndef _Included_com_mousebirdconsulting_maply_ViewState
#define _Included_com_mousebirdconsulting_maply_ViewState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_ViewState
 * Method:    initialise
 * Signature: (Lcom/mousebirdconsulting/maply/MapView;Lcom/mousebirdconsulting/maply/MaplyRenderer;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_ViewState_initialise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_ViewState
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_ViewState_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
