/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_VectorObject */

#ifndef _Included_com_mousebirdconsulting_maply_VectorObject
#define _Included_com_mousebirdconsulting_maply_VectorObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_VectorObject
 * Method:    fromGeoJSON
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebirdconsulting_maply_VectorObject_fromGeoJSON
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebirdconsulting_maply_VectorObject
 * Method:    fromGeoJSONAssembly
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebirdconsulting_maply_VectorObject_fromGeoJSONAssembly
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebirdconsulting_maply_VectorObject
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_VectorObject_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_VectorObject
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_VectorObject_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
