/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_QuadPagingLayer_LoadedTile */

#ifndef _Included_com_mousebirdconsulting_maply_QuadPagingLayer_LoadedTile
#define _Included_com_mousebirdconsulting_maply_QuadPagingLayer_LoadedTile
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
