/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_ChangeSet */

#ifndef _Included_com_mousebirdconsulting_maply_ChangeSet
#define _Included_com_mousebirdconsulting_maply_ChangeSet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_ChangeSet
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_ChangeSet_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_ChangeSet
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_ChangeSet_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
