/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_SphericalMercatorCoordSystem */

#ifndef _Included_com_mousebirdconsulting_maply_SphericalMercatorCoordSystem
#define _Included_com_mousebirdconsulting_maply_SphericalMercatorCoordSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_SphericalMercatorCoordSystem
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_SphericalMercatorCoordSystem_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebirdconsulting_maply_SphericalMercatorCoordSystem
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_SphericalMercatorCoordSystem_initialise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
