/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_VectorManager */

#ifndef _Included_com_mousebirdconsulting_maply_VectorManager
#define _Included_com_mousebirdconsulting_maply_VectorManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_VectorManager
 * Method:    addVector
 * Signature: (Lcom/mousebirdconsulting/maply/VectorObject;)J
 */
JNIEXPORT jlong JNICALL Java_com_mousebirdconsulting_maply_VectorManager_addVector
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_VectorManager
 * Method:    initialise
 * Signature: (Lcom/mousebirdconsulting/maply/MapScene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_VectorManager_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_VectorManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_VectorManager_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
