/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_Texture */

#ifndef _Included_com_mousebirdconsulting_maply_Texture
#define _Included_com_mousebirdconsulting_maply_Texture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_Texture
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_Texture_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_Texture
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_Texture_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
