/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_MapView */

#ifndef _Included_com_mousebirdconsulting_maply_MapView
#define _Included_com_mousebirdconsulting_maply_MapView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_MapView
 * Method:    setLoc
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_MapView_setLoc
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebirdconsulting_maply_MapView
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_MapView_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_MapView
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_MapView_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
