/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_QuadImageTileLayer_TileSource */

#ifndef _Included_com_mousebirdconsulting_maply_QuadImageTileLayer_TileSource
#define _Included_com_mousebirdconsulting_maply_QuadImageTileLayer_TileSource
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
