/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_PlateCarreeCoordSystem */

#ifndef _Included_com_mousebirdconsulting_maply_PlateCarreeCoordSystem
#define _Included_com_mousebirdconsulting_maply_PlateCarreeCoordSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_PlateCarreeCoordSystem
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_PlateCarreeCoordSystem_initialise
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
