/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebirdconsulting_maply_QuadImageTileLayer */

#ifndef _Included_com_mousebirdconsulting_maply_QuadImageTileLayer
#define _Included_com_mousebirdconsulting_maply_QuadImageTileLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeShutdown
 * Signature: (Lcom/mousebirdconsulting/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeShutdown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    setSimultaneousFetches
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_setSimultaneousFetches
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    initialise
 * Signature: (Lcom/mousebirdconsulting/maply/CoordSystem;Lcom/mousebirdconsulting/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_initialise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeStartLayer
 * Signature: (Lcom/mousebirdconsulting/maply/MapScene;Lcom/mousebirdconsulting/maply/MaplyRenderer;Lcom/mousebirdconsulting/maply/Point2d;Lcom/mousebirdconsulting/maply/Point2d;II)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeStartLayer
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeViewUpdate
 * Signature: (Lcom/mousebirdconsulting/maply/ViewState;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeViewUpdate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeEvalStep
 * Signature: (Lcom/mousebirdconsulting/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeEvalStep
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeRefresh
 * Signature: (Lcom/mousebirdconsulting/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeRefresh
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeTileDidLoad
 * Signature: (IIILandroid/graphics/Bitmap;Lcom/mousebirdconsulting/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeTileDidLoad
  (JNIEnv *, jobject, jint, jint, jint, jobject, jobject);

/*
 * Class:     com_mousebirdconsulting_maply_QuadImageTileLayer
 * Method:    nativeTileDidNotLoad
 * Signature: (IIILcom/mousebirdconsulting/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebirdconsulting_maply_QuadImageTileLayer_nativeTileDidNotLoad
  (JNIEnv *, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
