/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Triangle */

#ifndef _Included_com_mousebird_maply_Triangle
#define _Included_com_mousebird_maply_Triangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    setData
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Triangle_setData
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    getData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_mousebird_maply_Triangle_getData
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Triangle_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Triangle_initialise__
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    initialise
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Triangle_initialise__III
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_Triangle
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Triangle_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
