/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_LAZQuadReader */

#ifndef _Included_com_mousebird_maply_LAZQuadReader
#define _Included_com_mousebird_maply_LAZQuadReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setBounds
 * Signature: (DDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setBounds
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getLL
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_LAZQuadReader_getLL
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getUR
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_LAZQuadReader_getUR
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setZOffset
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setZOffset
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getZOffset
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_LAZQuadReader_getZOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setZoomLevels
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setZoomLevels
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getMinZoom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getMinZoom
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getMaxZoom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getMaxZoom
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setTilePoints
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setTilePoints
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getMinTilePoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getMinTilePoints
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getMaxTilePoints
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getMaxTilePoints
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setPointSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setPointSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getPointSize
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_LAZQuadReader_getPointSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setColorScale
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setColorScale
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getColorScale
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getColorScale
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setPointType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setPointType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    getPointType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LAZQuadReader_getPointType
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    setCoordSystemNative
 * Signature: (Lcom/mousebird/maply/CoordSystem;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_setCoordSystemNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    processTileNative
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;[BLcom/mousebird/maply/GeometryRawPoints;Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_processTileNative
  (JNIEnv *, jobject, jobject, jbyteArray, jobject, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LAZQuadReader
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LAZQuadReader_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
