/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_TexInfo */

#ifndef _Included_com_mousebird_maply_TexInfo
#define _Included_com_mousebird_maply_TexInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    getTexID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_TexInfo_getTexID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    setTexID
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexInfo_setTexID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    setTexCoordEntry
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexInfo_setTexCoordEntry
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    getTexCoordEntry
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_TexInfo_getTexCoordEntry
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
