/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_BillboardInfo */

#ifndef _Included_com_mousebird_maply_BillboardInfo
#define _Included_com_mousebird_maply_BillboardInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    setBillboardID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_setBillboardID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    getBillboardID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_BillboardInfo_getBillboardID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    addBillboard
 * Signature: (Lcom/mousebird/maply/Billboard;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_addBillboard
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    setColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_setColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    getColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_BillboardInfo_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    setZBufferRead
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_setZBufferRead
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    getZBufferRead
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_BillboardInfo_getZBufferRead
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    setZBufferWrite
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_setZBufferWrite
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    getZBufferWrite
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_BillboardInfo_getZBufferWrite
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_BillboardInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BillboardInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
