/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Matrix4f */

#ifndef _Included_com_mousebird_maply_Matrix4f
#define _Included_com_mousebird_maply_Matrix4f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Matrix4f
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix4f_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Matrix4f
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix4f_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Matrix4f
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix4f_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
