/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ParticleBatch */

#ifndef _Included_com_mousebird_maply_ParticleBatch
#define _Included_com_mousebird_maply_ParticleBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    setBatchSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleBatch_setBatchSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    getBatchSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_ParticleBatch_getBatchSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    addAttributes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleBatch_addAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleBatch_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleBatch_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ParticleBatch
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleBatch_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
