/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_GeometryRaw */

#ifndef _Included_com_mousebird_maply_GeometryRaw
#define _Included_com_mousebird_maply_GeometryRaw
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_GeometryRaw_valid
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    setType
 * Signature: (Lcom/mousebird/maply/GeometryRaw/GeometryType;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_setType
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    setTextureNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_setTextureNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    addPoints
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_addPoints
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    addNorms
 * Signature: ([DI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_addNorms
  (JNIEnv *, jobject, jdoubleArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    addTexCoords
 * Signature: ([FI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_addTexCoords
  (JNIEnv *, jobject, jfloatArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    addColors
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_addColors
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    addTriangles
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_addTriangles
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRaw
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRaw_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
