/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SimplePoly */

#ifndef _Included_com_mousebird_maply_SimplePoly
#define _Included_com_mousebird_maply_SimplePoly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/Texture;[FLjava/util/List;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_initialise__Lcom_mousebird_maply_Texture_2_3FLjava_util_List_2Ljava_util_List_2
  (JNIEnv *, jobject, jobject, jfloatArray, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addImage
 * Signature: (Lcom/mousebird/maply/Texture;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getTexture
 * Signature: ()Lcom/mousebird/maply/Texture;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SimplePoly_getTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addColor
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addColor
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SimplePoly_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addPt
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addPt
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addPts
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addPts
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    setPt
 * Signature: (ILcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_setPt
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addTexCoord
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addTexCoord
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    addTexCoords
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_addTexCoords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    setTexCoord
 * Signature: (ILcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_setTexCoord
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getPtsSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_SimplePoly_getPtsSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getTexCoordsSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_SimplePoly_getTexCoordsSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getPt
 * Signature: (I)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SimplePoly_getPt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    getTexCoord
 * Signature: (I)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SimplePoly_getTexCoord
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_initialise__
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SimplePoly
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SimplePoly_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
