/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_DrawableTweaker */

#ifndef _Included_com_mousebird_maply_DrawableTweaker
#define _Included_com_mousebird_maply_DrawableTweaker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_DrawableTweaker
 * Method:    tweakForFrame
 * Signature: (Lcom/mousebird/maply/Drawable;Lcom/mousebird/maply/RendererFrameInfo;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_DrawableTweaker_tweakForFrame
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_DrawableTweaker
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_DrawableTweaker_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_DrawableTweaker
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_DrawableTweaker_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_DrawableTweaker
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_DrawableTweaker_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
