/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Identifiable */

#ifndef _Included_com_mousebird_maply_Identifiable
#define _Included_com_mousebird_maply_Identifiable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Identifiable
 * Method:    genID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_Identifiable_genID
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
