/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Point2f */

#ifndef _Included_com_mousebird_maply_Point2f
#define _Included_com_mousebird_maply_Point2f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point2f_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point2f_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    setValue
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point2f_setValue
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point2f_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point2f_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point2f
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point2f_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
