/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_OpenGLStateOptimizer */

#ifndef _Included_com_mousebird_maply_OpenGLStateOptimizer
#define _Included_com_mousebird_maply_OpenGLStateOptimizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setActiveTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setActiveTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getActiveTexture
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getActiveTexture
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setDepthMask
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setDepthMask
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getDepthMask
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getDepthMask
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setEnableDepthTest
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setEnableDepthTest
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getEnableDepthTest
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getEnableDepthTest
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setDepthFunc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setDepthFunc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getDepthFuncVal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getDepthFuncVal
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setUseProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setUseProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getUseProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getUseProgram
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLStateOptimizer
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLStateOptimizer_reset
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
