/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_MapView */

#ifndef _Included_com_mousebird_maply_MapView
#define _Included_com_mousebird_maply_MapView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_MapView
 * Method:    minHeightAboveSurface
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_MapView_minHeightAboveSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    maxHeightAboveSurface
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_MapView_maxHeightAboveSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    setLoc
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_setLoc
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    getLoc
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_MapView_getLoc
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    setRot
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_setRot
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    getRot
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_MapView_getRot
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    calcModelViewMatrix
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_MapView_calcModelViewMatrix
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    pointOnPlaneFromScreen
 * Signature: (Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Matrix4d;Lcom/mousebird/maply/Point2d;Z)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_MapView_pointOnPlaneFromScreen
  (JNIEnv *, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    pointOnScreenFromPlane
 * Signature: (Lcom/mousebird/maply/Point3d;Lcom/mousebird/maply/Matrix4d;Lcom/mousebird/maply/Point2d;)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_MapView_pointOnScreenFromPlane
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    nativeClone
 * Signature: (Lcom/mousebird/maply/MapView;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_nativeClone
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_MapView
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapView_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
