/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_GeometryRawPoints */

#ifndef _Included_com_mousebird_maply_GeometryRawPoints
#define _Included_com_mousebird_maply_GeometryRawPoints
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_GeometryRawPoints_valid
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addIntValues
 * Signature: (Ljava/lang/String;[II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addIntValues
  (JNIEnv *, jobject, jstring, jintArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addFloatValues
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addFloatValues
  (JNIEnv *, jobject, jstring, jfloatArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addPoint2fValues
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addPoint2fValues
  (JNIEnv *, jobject, jstring, jfloatArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addPoint3fValues
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addPoint3fValues
  (JNIEnv *, jobject, jstring, jfloatArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addPoint3dValues
 * Signature: (Ljava/lang/String;[DI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addPoint3dValues
  (JNIEnv *, jobject, jstring, jdoubleArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addPoint4fValues
 * Signature: (Ljava/lang/String;[FI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_addPoint4fValues
  (JNIEnv *, jobject, jstring, jfloatArray, jint);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    addAttribute
 * Signature: (Ljava/lang/String;Lcom/mousebird/maply/GeometryRawPoints/Type;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_GeometryRawPoints_addAttribute
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GeometryRawPoints
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryRawPoints_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
