/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Proj4CoordSystem */

#ifndef _Included_com_mousebird_maply_Proj4CoordSystem
#define _Included_com_mousebird_maply_Proj4CoordSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Proj4CoordSystem
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Proj4CoordSystem_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Proj4CoordSystem
 * Method:    initialise
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Proj4CoordSystem_initialise
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
