/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_CoordSystemDisplayAdapter */

#ifndef _Included_com_mousebird_maply_CoordSystemDisplayAdapter
#define _Included_com_mousebird_maply_CoordSystemDisplayAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
