/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SingleVertexAttribute */

#ifndef _Included_com_mousebird_maply_SingleVertexAttribute
#define _Included_com_mousebird_maply_SingleVertexAttribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setVec4Values
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setVec4Values
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getVec4Values
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getVec4Values
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setVec3Values
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setVec3Values
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getVec3Values
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getVec3Values
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setVec2Values
 * Signature: ([F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setVec2Values
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getVec2Values
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getVec2Values
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setFloatVal
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setFloatVal
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getFloatVal
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getFloatVal
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setIntVal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setIntVal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getIntVal
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getIntVal
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    setColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_setColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    getColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SingleVertexAttribute_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    initialise
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_initialise
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mousebird_maply_SingleVertexAttribute
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttribute_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
