/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SceneRendererES */

#ifndef _Included_com_mousebird_maply_SceneRendererES
#define _Included_com_mousebird_maply_SceneRendererES
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mousebird_maply_SceneRendererES_ZBufferMode_ON
#define com_mousebird_maply_SceneRendererES_ZBufferMode_ON 1L
#undef com_mousebird_maply_SceneRendererES_ZBufferMode_OFF
#define com_mousebird_maply_SceneRendererES_ZBufferMode_OFF 2L
#undef com_mousebird_maply_SceneRendererES_ZBufferMode_DEFAULT
#define com_mousebird_maply_SceneRendererES_ZBufferMode_DEFAULT 3L
/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    initialise
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_initialise
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setup
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setRenderUntil
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setRenderUntil
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    addContinuousRenderRequest
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_addContinuousRenderRequest
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    removeContinuosRenderRequest
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_removeContinuosRenderRequest
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    forceDrawNextFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_forceDrawNextFrame
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setClearColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setClearColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    getFrameBufferSize
 * Signature: ()Lcom/mousebird/maply/Point2f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SceneRendererES_getFrameBufferSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    getScene
 * Signature: ()Lcom/mousebird/maply/Scene;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SceneRendererES_getScene
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    getView
 * Signature: ()Lcom/mousebird/maply/View;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SceneRendererES_getView
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    getScale
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_SceneRendererES_getScale
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    findDrawables
 * Signature: (Lcom/mousebird/maply/Cullable;Lcom/mousebird/maply/GlobeView;Lcom/mousebird/maply/Point2f;Lcom/mousebird/maply/Matrix4d;Lcom/mousebird/maply/Point3d;Lcom/mousebird/maply/RendererFrameInfo;Lcom/mousebird/maply/Mbr;ZLjava/util/Vector;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_findDrawables
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jobject, jboolean, jobject, jint);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    viewDidChange
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_SceneRendererES_viewDidChange
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setTriggerDraw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setTriggerDraw
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setZBufferMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setZBufferMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setScene
 * Signature: (Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setScene
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setDoCulling
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setDoCulling
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setPerfInterval
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setPerfInterval
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setUseViewChanged
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setUseViewChanged
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setView
 * Signature: (Lcom/mousebird/maply/View;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setView
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SceneRendererES
 * Method:    setExtraFrameMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SceneRendererES_setExtraFrameMode
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
