/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_BaseInfo */

#ifndef _Included_com_mousebird_maply_BaseInfo
#define _Included_com_mousebird_maply_BaseInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setEnable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setEnable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setDrawOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setDrawOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setDrawPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setDrawPriority
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setMinVis
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setMinVis
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setMaxVis
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setMaxVis
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    setFade
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_setFade
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_BaseInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_BaseInfo_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
