/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Drawable */

#ifndef _Included_com_mousebird_maply_Drawable
#define _Included_com_mousebird_maply_Drawable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getProgram
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_Drawable_getProgram
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setProgram
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setProgram
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupGL
 * Signature: (Lcom/mousebird/maply/WhirlyKitGLSetupInfo;Lcom/mousebird/maply/OpenGLMemManager;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setupGL__Lcom_mousebird_maply_WhirlyKitGLSetupInfo_2Lcom_mousebird_maply_OpenGLMemManager_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupGL
 * Signature: (Lcom/mousebird/maply/WhirlyKitGLSetupInfo;Lcom/mousebird/maply/OpenGLMemManager;II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setupGL__Lcom_mousebird_maply_WhirlyKitGLSetupInfo_2Lcom_mousebird_maply_OpenGLMemManager_2II
  (JNIEnv *, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    tearDownGL
 * Signature: (Lcom/mousebird/maply/OpenGLMemManager;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_tearDownGL
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    singleVertexSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_singleVertexSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupVAO
 * Signature: (Lcom/mousebird/maply/OpenGLES2Program;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_setupVAO
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    draw
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_draw
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getDrawPriority
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_getDrawPriority
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    isOn
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_isOn
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setOnOff
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setOnOff
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setEnableTimeRange
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setEnableTimeRange
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    hasAlpha
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_hasAlpha
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setAlpha
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_setAlpha
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getLocalMbrPoint2dLL
 * Signature: ()Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getLocalMbrPoint2dLL
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getLocalMbrPoint2dUr
 * Signature: ()Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getLocalMbrPoint2dUr
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setLocalMbr
 * Signature: (Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setLocalMbr
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setDrawPriority
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setDrawPriority
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setDrawOffset
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setDrawOffset
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getDrawOffset
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getDrawOffset
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setTexId
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setTexId
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setTexIds
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setTexIds
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getColorPartR
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getColorPartR
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getColorPartG
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getColorPartG
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getColorPartB
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getColorPartB
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getColorPartA
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getColorPartA
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setVisibleRange
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setVisibleRange
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getVisibleRangeMinVis
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getVisibleRangeMinVis
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getVisibleRangeMaxVis
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getVisibleRangeMaxVis
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getVisibleRangeMinVisBand
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getVisibleRangeMinVisBand
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getVisibleRangeMaxVisBand
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getVisibleRangeMaxVisBand
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setViewerVisibility
 * Signature: (DDLcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setViewerVisibility
  (JNIEnv *, jobject, jdouble, jdouble, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getViewerVisibilityMinDist
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Drawable_getViewerVisibilityMinDist
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getViewerVisibilityMaxdist
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Drawable_getViewerVisibilityMaxdist
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getViewerVisibilityCenter
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getViewerVisibilityCenter
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setFade
 * Signature: (DD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setFade
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Drawable_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setRequestZBuffer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setRequestZBuffer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getRequestZBuffer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_getRequestZBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setWriteZBuffer
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setWriteZBuffer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getWriteZBuffer
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_getWriteZBuffer
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addPoint
 * Signature: (Lcom/mousebird/maply/Point3f;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_addPoint__Lcom_mousebird_maply_Point3f_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addPoint
 * Signature: (Lcom/mousebird/maply/Point3d;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_addPoint__Lcom_mousebird_maply_Point3d_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getPoint
 * Signature: (I)Lcom/mousebird/maply/Point3f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getPoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addTexCoord
 * Signature: (ILcom/mousebird/maply/Point2f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addTexCoord
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addNormal
 * Signature: (Lcom/mousebird/maply/Point3f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addNormal__Lcom_mousebird_maply_Point3f_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addNormal
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addNormal__Lcom_mousebird_maply_Point3d_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    compareVertexAttributes
 * Signature: (Ljava/util/List;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Drawable_compareVertexAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setVertexAttributes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setVertexAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addVertexAttributes
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addVertexAttributes
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttributeValue
 * Signature: (ILcom/mousebird/maply/Point2f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addAttributeValue__ILcom_mousebird_maply_Point2f_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttributeValue
 * Signature: (ILcom/mousebird/maply/Point3f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addAttributeValue__ILcom_mousebird_maply_Point3f_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttributeValue
 * Signature: (ILcom/mousebird/maply/Point4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addAttributeValue__ILcom_mousebird_maply_Point4f_2
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttributeValue
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addAttributeValue__IFFFF
  (JNIEnv *, jobject, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttributeValue
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addAttributeValue__IF
  (JNIEnv *, jobject, jint, jfloat);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addTriangle
 * Signature: (Lcom/mousebird/maply/Triangle;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addTriangle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getTexID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_getTexID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getTexInfo
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getTexInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addAttribute
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_addAttribute
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getNumPoint
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_getNumPoint
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getNumTris
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Drawable_getNumTris
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    reserveNumPoint
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_reserveNumPoint
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    reserveNumTris
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_reserveNumTris
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    reserveNumTexCoords
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_reserveNumTexCoords
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    reserveNumNorms
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_reserveNumNorms
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    reserveNumColors
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_reserveNumColors
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setMatrix
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setMatrix
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getMatrix
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getMatrix
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    applySubTexture
 * Signature: (ILcom/mousebird/maply/SubTexture;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_applySubTexture
  (JNIEnv *, jobject, jint, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    updateRenderer
 * Signature: (Lcom/mousebird/maply/SceneRendererES;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_updateRenderer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    asData
 * Signature: (ZZ)Lcom/mousebird/maply/RawData;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_asData
  (JNIEnv *, jobject, jboolean, jboolean);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    asVextexAndElementData
 * Signature: (Lcom/mousebird/maply/MutableRawData;Lcom/mousebird/maply/MutableRawData;ILcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_asVextexAndElementData
  (JNIEnv *, jobject, jobject, jobject, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    getVertexAttributes
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Drawable_getVertexAttributes
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupTexCoordEntry
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setupTexCoordEntry
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    drawOGL2
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_drawOGL2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addPointToBuffer
 * Signature: (Ljava/lang/String;ILcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addPointToBuffer
  (JNIEnv *, jobject, jstring, jint, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupAdditionalVAO
 * Signature: (Lcom/mousebird/maply/OpenGLES2Program;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setupAdditionalVAO
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    bindAdditionalRenderObjects
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_bindAdditionalRenderObjects
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    postDrawCallBack
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_postDrawCallBack
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    setupStandardAttributes
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_setupStandardAttributes
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    addTweaker
 * Signature: (Lcom/mousebird/maply/DrawableTweaker;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_addTweaker
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    removeTweaker
 * Signature: (Lcom/mousebird/maply/DrawableTweaker;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_removeTweaker
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    runTweakers
 * Signature: (Lcom/mousebird/maply/RendererFrameInfo;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_runTweakers
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    initialise
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_initialise__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    initialise
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_initialise__Ljava_lang_String_2II
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Drawable
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Drawable_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
