/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_RendererFrameInfo */

#ifndef _Included_com_mousebird_maply_RendererFrameInfo
#define _Included_com_mousebird_maply_RendererFrameInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setOGLVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setOGLVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getOGLVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_RendererFrameInfo_getOGLVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setSceneRendererES
 * Signature: (Lcom/mousebird/maply/SceneRendererES;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setSceneRendererES
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getSceneRendererES
 * Signature: ()Lcom/mousebird/maply/SceneRendererES;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getSceneRendererES
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setView
 * Signature: (Lcom/mousebird/maply/View;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setView
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getView
 * Signature: ()Lcom/mousebird/maply/View;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getView
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setModelTrans
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setModelTrans
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getModelTrans
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getModelTrans
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setViewTrans
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setViewTrans
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getViewTrans
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getViewTrans
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setModelTrans4d
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setModelTrans4d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getModelTrans4d
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getModelTrans4d
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setViewTrans4d
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setViewTrans4d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getViewTrans4d
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getViewTrans4d
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setProjMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setProjMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getProjMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getProjMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setProjMat4d
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setProjMat4d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getProjMat4d
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getProjMat4d
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setMvpNormalMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setMvpNormalMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getMvpNormalMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getMvpNormalMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setViewAndModelMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setViewAndModelMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getViewAndModelMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getViewAndModelMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setViewAndModelMat4d
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setViewAndModelMat4d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getViewAndModelMat4d
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getViewAndModelMat4d
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setMvpMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setMvpMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getMvpMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getMvpMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setViewModelNormalMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setViewModelNormalMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getViewModelNormalMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getViewModelNormalMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setPvMat4d
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setPvMat4d
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getPvMat4d
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getPvMat4d
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setPvMat
 * Signature: (Lcom/mousebird/maply/Matrix4f;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setPvMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getPvMat
 * Signature: ()Lcom/mousebird/maply/Matrix4f;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getPvMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setOffSetMatrices
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setOffSetMatrices
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getOffSetMatrices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getOffSetMatrices
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setScene
 * Signature: (Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setScene
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getScene
 * Signature: ()Lcom/mousebird/maply/Scene;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getScene
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setFrameLen
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setFrameLen
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getFrameLen
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_RendererFrameInfo_getFrameLen
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setCurrentTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setCurrentTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getCurrentTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_RendererFrameInfo_getCurrentTime
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setEyeVec
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setEyeVec
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getEyeVec
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getEyeVec
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setFullEyeVec
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setFullEyeVec
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getFullEyeVec
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getFullEyeVec
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setEyePos
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setEyePos
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getEyePos
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getEyePos
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setDispCenter
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setDispCenter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getDispCenter
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getDispCenter
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setHeightAboveSurface
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setHeightAboveSurface
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getHeightAboveSurface
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_RendererFrameInfo_getHeightAboveSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setScreenSizeInDisplaysCoords
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setScreenSizeInDisplaysCoords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getScreenSizeInDisplaysCoords
 * Signature: ()Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getScreenSizeInDisplaysCoords
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setOpenGLES2Program
 * Signature: (Lcom/mousebird/maply/OpenGLES2Program;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setOpenGLES2Program
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getOpenGLES2Program
 * Signature: ()Lcom/mousebird/maply/OpenGLES2Program;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getOpenGLES2Program
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    setStateOptimizer
 * Signature: (Lcom/mousebird/maply/OpenGLStateOptimizer;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RendererFrameInfo_setStateOptimizer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_RendererFrameInfo
 * Method:    getStateOptimizer
 * Signature: ()Lcom/mousebird/maply/OpenGLStateOptimizer;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_RendererFrameInfo_getStateOptimizer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
