/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Shader */

#ifndef _Included_com_mousebird_maply_Shader
#define _Included_com_mousebird_maply_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Shader
 * Method:    valid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_valid
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_Shader_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    setUniform
 * Signature: (Ljava/lang/String;D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_setUniform__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    setUniform
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_setUniform__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    setUniform
 * Signature: (Ljava/lang/String;DD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_setUniform__Ljava_lang_String_2DD
  (JNIEnv *, jobject, jstring, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    setUniform
 * Signature: (Ljava/lang/String;DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_setUniform__Ljava_lang_String_2DDD
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    setUniform
 * Signature: (Ljava/lang/String;DDDD)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Shader_setUniform__Ljava_lang_String_2DDDD
  (JNIEnv *, jobject, jstring, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Shader_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    initialise
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Shader_initialise
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_mousebird_maply_Shader
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Shader_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
