/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ParticleSystemManager */

#ifndef _Included_com_mousebird_maply_ParticleSystemManager
#define _Included_com_mousebird_maply_ParticleSystemManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    addParticleSystems
 * Signature: (Ljava/util/List;Lcom/mousebird/maply/AttrDictionary;JLcom/mousebird/maply/ChangeSet;)J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_ParticleSystemManager_addParticleSystems
  (JNIEnv *, jobject, jobject, jobject, jlong, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    removeParticleSystems
 * Signature: (JJLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_removeParticleSystems
  (JNIEnv *, jobject, jlong, jlong, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    initialize
 * Signature: (Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
