/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Affine2d */

#ifndef _Included_com_mousebird_maply_Affine2d
#define _Included_com_mousebird_maply_Affine2d
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mousebird_maply_Affine2d_TYPE_SCALE
#define com_mousebird_maply_Affine2d_TYPE_SCALE 1L
#undef com_mousebird_maply_Affine2d_TYPE_TRANS
#define com_mousebird_maply_Affine2d_TYPE_TRANS 2L
/*
 * Class:     com_mousebird_maply_Affine2d
 * Method:    matrix
 * Signature: ()Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Affine2d_matrix
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Affine2d
 * Method:    multiply
 * Signature: (Lcom/mousebird/maply/Point2d;)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Affine2d_multiply
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Affine2d
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Affine2d_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Affine2d
 * Method:    initialise
 * Signature: (DDI)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Affine2d_initialise
  (JNIEnv *, jobject, jdouble, jdouble, jint);

/*
 * Class:     com_mousebird_maply_Affine2d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Affine2d_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
