/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_QuadPagingLayer */

#ifndef _Included_com_mousebird_maply_QuadPagingLayer
#define _Included_com_mousebird_maply_QuadPagingLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    geoBoundsForTileNative
 * Signature: (IIILcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_geoBoundsForTileNative
  (JNIEnv *, jobject, jint, jint, jint, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeShutdown
 * Signature: (Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeShutdown
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    setSimultaneousFetches
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_setSimultaneousFetches
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    setUseTargetZoomLevel
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_setUseTargetZoomLevel
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeSetSingleLevelLoading
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeSetSingleLevelLoading
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    setImportance
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_setImportance
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystem;Lcom/mousebird/maply/QuadPagingLayer/PagingInterface;Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_initialise
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeStartLayer
 * Signature: (Lcom/mousebird/maply/MapScene;Lcom/mousebird/maply/MaplyRenderer;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeStartLayer
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeViewUpdate
 * Signature: (Lcom/mousebird/maply/ViewState;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeViewUpdate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeEvalStep
 * Signature: (Lcom/mousebird/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeEvalStep
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeRefresh
 * Signature: (Lcom/mousebird/maply/ChangeSet;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeRefresh
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeTileDidLoad
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeTileDidLoad
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_QuadPagingLayer
 * Method:    nativeTileDidNotLoad
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadPagingLayer_nativeTileDidNotLoad
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
