/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_AttrDictionary */

#ifndef _Included_com_mousebird_maply_AttrDictionary
#define _Included_com_mousebird_maply_AttrDictionary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_AttrDictionary_getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getInt
 * Signature: (Ljava/lang/String;)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_AttrDictionary_getInt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    getDouble
 * Signature: (Ljava/lang/String;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_AttrDictionary_getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_AttrDictionary
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_AttrDictionary_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
