/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ScreenObject */

#ifndef _Included_com_mousebird_maply_ScreenObject
#define _Included_com_mousebird_maply_ScreenObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    addPoly
 * Signature: (Lcom/mousebird/maply/SimplePoly;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_addPoly
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    getPoly
 * Signature: (I)Lcom/mousebird/maply/SimplePoly;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_ScreenObject_getPoly
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    getPolysSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_ScreenObject_getPolysSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    addString
 * Signature: (Lcom/mousebird/maply/StringWrapper;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_addString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    getString
 * Signature: (I)Lcom/mousebird/maply/StringWrapper;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_ScreenObject_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    getStringsSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_ScreenObject_getStringsSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    addImage
 * Signature: (Landroid/graphics/Bitmap;[FFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_addImage
  (JNIEnv *, jobject, jobject, jfloatArray, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    addScreenObject
 * Signature: (Lcom/mousebird/maply/ScreenObject;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_addScreenObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ScreenObject
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ScreenObject_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
