/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Batch */

#ifndef _Included_com_mousebird_maply_Batch
#define _Included_com_mousebird_maply_Batch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Batch
 * Method:    setBatchID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_setBatchID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    getBatchID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Batch_getBatchID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    setOffSet
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_setOffSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    getOffSet
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Batch_getOffSet
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    setLen
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_setLen
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    getLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Batch_getLen
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    setActive
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_setActive
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    getActive
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Batch_getActive
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    setStartTime
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_setStartTime
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    getStartTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Batch_getStartTime
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Batch
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Batch_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
