/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_GlobeView */

#ifndef _Included_com_mousebird_maply_GlobeView
#define _Included_com_mousebird_maply_GlobeView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    pointOnSphereFromScreen
 * Signature: (Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Matrix4d;Lcom/mousebird/maply/Point2d;Z)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_pointOnSphereFromScreen
  (JNIEnv *, jobject, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    pointOnScreenFromSphere
 * Signature: (Lcom/mousebird/maply/Point3d;Lcom/mousebird/maply/Matrix4d;Lcom/mousebird/maply/Point2d;)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_pointOnScreenFromSphere
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    minHeightAboveSurface
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_GlobeView_minHeightAboveSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    maxHeightAboveSurface
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_GlobeView_maxHeightAboveSurface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    getRotQuat
 * Signature: ()Lcom/mousebird/maply/Quaternion;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_getRotQuat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    setRotQuatNative
 * Signature: (Lcom/mousebird/maply/Quaternion;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_setRotQuatNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    getLoc
 * Signature: ()Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_getLoc
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    getHeight
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_GlobeView_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    setHeight
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_setHeight
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    makeRotationToGeoCoord
 * Signature: (DDZ)Lcom/mousebird/maply/Quaternion;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_makeRotationToGeoCoord
  (JNIEnv *, jobject, jdouble, jdouble, jboolean);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    prospectiveUp
 * Signature: (Lcom/mousebird/maply/Quaternion;)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_prospectiveUp
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    pointUnproject
 * Signature: (Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;Z)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_GlobeView_pointUnproject
  (JNIEnv *, jobject, jobject, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    nativeClone
 * Signature: (Lcom/mousebird/maply/GlobeView;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_nativeClone
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GlobeView
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GlobeView_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
