/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_CullTree */

#ifndef _Included_com_mousebird_maply_CullTree
#define _Included_com_mousebird_maply_CullTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    getTopCullable
 * Signature: ()Lcom/mousebird/maply/Cullable;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_CullTree_getTopCullable
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    getCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_CullTree_getCount
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    dumpStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CullTree_dumpStats
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CullTree_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CullTree_initialise
  (JNIEnv *, jobject, jobject, jobject, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_CullTree
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CullTree_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
