/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_StringWrapper */

#ifndef _Included_com_mousebird_maply_StringWrapper
#define _Included_com_mousebird_maply_StringWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_StringWrapper_setSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    getSize
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_mousebird_maply_StringWrapper_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    setMat
 * Signature: (Lcom/mousebird/maply/Matrix3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_StringWrapper_setMat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    getMat
 * Signature: ()Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_StringWrapper_getMat
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_StringWrapper_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_StringWrapper_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_StringWrapper
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_StringWrapper_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
