/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_MapView_ViewWatcher */

#ifndef _Included_com_mousebird_maply_MapView_ViewWatcher
#define _Included_com_mousebird_maply_MapView_ViewWatcher
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
