/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_TexCoord */

#ifndef _Included_com_mousebird_maply_TexCoord
#define _Included_com_mousebird_maply_TexCoord
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    u
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_TexCoord_u
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    y
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_TexCoord_y
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexCoord_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexCoord_initialise__
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    initialise
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexCoord_initialise__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_TexCoord
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_TexCoord_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
