/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_LabelInfo */

#ifndef _Included_com_mousebird_maply_LabelInfo
#define _Included_com_mousebird_maply_LabelInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setTextColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setTextColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setBackgroundColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setBackgroundColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setTypeface
 * Signature: (Landroid/graphics/Typeface;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setTypeface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setFontSize
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setFontSize
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setLayoutImportance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setLayoutImportance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    setLayoutPlacement
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_setLayoutPlacement
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    getTypeface
 * Signature: ()Landroid/graphics/Typeface;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_LabelInfo_getTypeface
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    getTextColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LabelInfo_getTextColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    getBackColor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_LabelInfo_getBackColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_LabelInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_LabelInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
