/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_OpenGLESAttribute */

#ifndef _Included_com_mousebird_maply_OpenGLESAttribute
#define _Included_com_mousebird_maply_OpenGLESAttribute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    isArray
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLESAttribute_isArray
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    isType
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLESAttribute_isType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_OpenGLESAttribute_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    setIndex
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_setIndex
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    getIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLESAttribute_getIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    setSize
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_setSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLESAttribute_getSize
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLESAttribute_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLESAttribute
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLESAttribute_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
