/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_MapboxVectorTileParser */

#ifndef _Included_com_mousebird_maply_MapboxVectorTileParser
#define _Included_com_mousebird_maply_MapboxVectorTileParser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_MapboxVectorTileParser
 * Method:    parseDataNative
 * Signature: ([BDDDD)[Lcom/mousebird/maply/VectorObject;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mousebird_maply_MapboxVectorTileParser_parseDataNative
  (JNIEnv *, jobject, jbyteArray, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_MapboxVectorTileParser
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapboxVectorTileParser_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapboxVectorTileParser
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapboxVectorTileParser_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_MapboxVectorTileParser
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapboxVectorTileParser_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
