/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_QuadTracker */

#ifndef _Included_com_mousebird_maply_QuadTracker
#define _Included_com_mousebird_maply_QuadTracker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    tiles
 * Signature: ([Lcom/mousebird/maply/QuadTrackerPointReturn;I)[Lcom/mousebird/maply/QuadTrackerPointReturn;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mousebird_maply_QuadTracker_tiles
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    addTile
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_addTile
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    removeTile
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_removeTile
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    setCoordSystem
 * Signature: (Lcom/mousebird/maply/CoordSystem;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_setCoordSystem
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    setMinLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_setMinLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    getMinLevel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_QuadTracker_getMinLevel
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    setAdapter
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_setAdapter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    setRenderer
 * Signature: (Lcom/mousebird/maply/MaplyRenderer;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_setRenderer
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/GlobeView;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_QuadTracker
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTracker_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
