/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Matrix3d */

#ifndef _Included_com_mousebird_maply_Matrix3d
#define _Included_com_mousebird_maply_Matrix3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix3d_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix3d_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Matrix3d_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    inverse
 * Signature: ()Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_inverse
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    transpose
 * Signature: ()Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_transpose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    multiply
 * Signature: (Lcom/mousebird/maply/Point3d;)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_multiply__Lcom_mousebird_maply_Point3d_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    traslateX
 * Signature: (DD)Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_traslateX
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    multiplyTrasX
 * Signature: (DDLcom/mousebird/maply/Point2d;)Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_multiplyTrasX
  (JNIEnv *, jclass, jdouble, jdouble, jobject);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    scaleX
 * Signature: (DD)Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_scaleX
  (JNIEnv *, jclass, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Matrix3d
 * Method:    multiply
 * Signature: (Lcom/mousebird/maply/Matrix3d;)Lcom/mousebird/maply/Matrix3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Matrix3d_multiply__Lcom_mousebird_maply_Matrix3d_2
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
