/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_InternalLabel */

#ifndef _Included_com_mousebird_maply_InternalLabel
#define _Included_com_mousebird_maply_InternalLabel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setLoc
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setLoc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setRotation
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setRotation
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setText
 * Signature: ([II)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setText
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setOffset
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setOffset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setSelectable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setSelectable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    setLayoutImportance
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_setLayoutImportance
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_InternalLabel
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_InternalLabel_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
