/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SelectionManager */

#ifndef _Included_com_mousebird_maply_SelectionManager
#define _Included_com_mousebird_maply_SelectionManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SelectionManager
 * Method:    pickObject
 * Signature: (Lcom/mousebird/maply/View;Lcom/mousebird/maply/Point2d;)J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_SelectionManager_pickObject
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SelectionManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SelectionManager_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SelectionManager
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SelectionManager_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SelectionManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SelectionManager_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
