/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Point4f */

#ifndef _Included_com_mousebird_maply_Point4f
#define _Included_com_mousebird_maply_Point4f
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    getX
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point4f_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    getY
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point4f_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    getZ
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point4f_getZ
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    getW
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_Point4f_getW
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    setValue
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point4f_setValue
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point4f_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point4f_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point4f
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point4f_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
