/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SingleVertexAttributeInfo */

#ifndef _Included_com_mousebird_maply_SingleVertexAttributeInfo
#define _Included_com_mousebird_maply_SingleVertexAttributeInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    setName
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_setName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    setType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_setType
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    getType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_getType
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleVertexAttributeInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleVertexAttributeInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
