/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Cullable */

#ifndef _Included_com_mousebird_maply_Cullable
#define _Included_com_mousebird_maply_Cullable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    addDrawable
 * Signature: (Lcom/mousebird/maply/CullTree;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Drawable;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Cullable_addDrawable
  (JNIEnv *, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    getDrawables
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Cullable_getDrawables
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    getChildDrawables
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Cullable_getChildDrawables
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    hasChildren
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Cullable_hasChildren
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    isEmpty
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_Cullable_isEmpty
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    getChild
 * Signature: (I)Lcom/mousebird/maply/Cullable;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Cullable_getChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    getMbrLL
 * Signature: ()Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Cullable_getMbrLL
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    getMbrUr
 * Signature: ()Lcom/mousebird/maply/Point2d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Cullable_getMbrUr
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    countNodes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_Cullable_countNodes
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Cullable_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;Lcom/mousebird/maply/Point2d;Lcom/mousebird/maply/Point2d;I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Cullable_initialise
  (JNIEnv *, jobject, jobject, jobject, jobject, jint);

/*
 * Class:     com_mousebird_maply_Cullable
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Cullable_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
