/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_OpenGLES2Program */

#ifndef _Included_com_mousebird_maply_OpenGLES2Program
#define _Included_com_mousebird_maply_OpenGLES2Program
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    isValid
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_isValid
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;Lcom/mousebird/maply/Point2f;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2Lcom_mousebird_maply_Point2f_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;Lcom/mousebird/maply/Point3f;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2Lcom_mousebird_maply_Point3f_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;Lcom/mousebird/maply/Point4f;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2Lcom_mousebird_maply_Point4f_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;Lcom/mousebird/maply/Matrix4f;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2Lcom_mousebird_maply_Matrix4f_2
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setUniform
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setUniform__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    setTexture
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_setTexture
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    hasLights
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_OpenGLES2Program_hasLights
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    findAttribute
 * Signature: (Ljava/lang/String;)Lcom/mousebird/maply/OpenGLESAttribute;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_OpenGLES2Program_findAttribute
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mousebird_maply_OpenGLES2Program_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    getProgram
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLES2Program_getProgram
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    bindTextures
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLES2Program_bindTextures
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    cleanUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLES2Program_cleanUp
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    initialise
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLES2Program_initialise__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLES2Program_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLES2Program_initialise__
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLES2Program
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLES2Program_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
