/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_MapScene */

#ifndef _Included_com_mousebird_maply_MapScene
#define _Included_com_mousebird_maply_MapScene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_MapScene
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapScene_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_MapScene
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystemDisplayAdapter;Lcom/mousebird/maply/CharRenderer;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapScene_initialise
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_MapScene
 * Method:    addChangesNative
 * Signature: (Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapScene_addChangesNative
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_MapScene
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_MapScene_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
