/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SubTexture */

#ifndef _Included_com_mousebird_maply_SubTexture
#define _Included_com_mousebird_maply_SubTexture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    setFromTex
 * Signature: (Lcom/mousebird/maply/TexCoord;Lcom/mousebird/maply/TexCoord;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_setFromTex
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    procressTexCoord
 * Signature: (Lcom/mousebird/maply/TexCoord;)Lcom/mousebird/maply/TexCoord;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_SubTexture_procressTexCoord
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    processTexCoords
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_processTexCoords
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    setTexID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_setTexID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    getTexID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_SubTexture_getTexID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SubTexture
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SubTexture_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
