/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ParticleSystem */

#ifndef _Included_com_mousebird_maply_ParticleSystem
#define _Included_com_mousebird_maply_ParticleSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    makeDefault
 * Signature: ()Lcom/mousebird/maply/ParticleSystem;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_ParticleSystem_makeDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    generateParticle
 * Signature: ()Lcom/mousebird/maply/Particle;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_ParticleSystem_generateParticle
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setLoc
 * Signature: (Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setLoc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMinLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMinLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMaxLength
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMaxLength
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMinLifetime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMinLifetime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMaxLifetime
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMaxLifetime
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMinPhi
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMinPhi
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMaxPhi
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMaxPhi
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMinVis
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMinVis
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    setMaxVis
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_setMaxVis
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystem
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystem_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
