/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ParticleSystemManager */

#ifndef _Included_com_mousebird_maply_ParticleSystemManager
#define _Included_com_mousebird_maply_ParticleSystemManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    addParticleSystem
 * Signature: (Lcom/mousebird/maply/ParticleSystem;Lcom/mousebird/maply/ChangeSet;)J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_ParticleSystemManager_addParticleSystem
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    addParticleBatch
 * Signature: (JLcom/mousebird/maply/ParticleBatch;Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_addParticleBatch
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    enableParticleSystem
 * Signature: (JZLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_enableParticleSystem
  (JNIEnv *, jobject, jlong, jboolean, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    removeParticleSystem
 * Signature: (JLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_removeParticleSystem
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    housekeeping
 * Signature: (DLcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_housekeeping
  (JNIEnv *, jobject, jdouble, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    initialize
 * Signature: (Lcom/mousebird/maply/Scene;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_initialize
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_ParticleSystemManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_ParticleSystemManager_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
