/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ViewState */

#ifndef _Included_com_mousebird_maply_ViewState
#define _Included_com_mousebird_maply_ViewState
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_ViewState
 * Method:    isEqual
 * Signature: (Lcom/mousebird/maply/ViewState;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_ViewState_isEqual
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
