/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_View */

#ifndef _Included_com_mousebird_maply_View
#define _Included_com_mousebird_maply_View
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_View
 * Method:    calcModelViewMatrix
 * Signature: ()Lcom/mousebird/maply/Matrix4d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_View_calcModelViewMatrix
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_View
 * Method:    heightForMapScale
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_View_heightForMapScale
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_View
 * Method:    currentMapZoom
 * Signature: (DDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_View_currentMapZoom
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_View
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_View_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
