/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_SingleBillboardPoly */

#ifndef _Included_com_mousebird_maply_SingleBillboardPoly
#define _Included_com_mousebird_maply_SingleBillboardPoly
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    addPoint
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_addPoint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    addTexCoord
 * Signature: (Lcom/mousebird/maply/Point2d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_addTexCoord
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    addColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_addColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    getColor
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_mousebird_maply_SingleBillboardPoly_getColor
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    setTexID
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_setTexID
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    getTexID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_SingleBillboardPoly_getTexID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    addVertexAttribute
 * Signature: (Lcom/mousebird/maply/VertexAttribute;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_addVertexAttribute
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_SingleBillboardPoly
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_SingleBillboardPoly_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
