/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_RawData */

#ifndef _Included_com_mousebird_maply_RawData
#define _Included_com_mousebird_maply_RawData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_RawData
 * Method:    getRawData
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_com_mousebird_maply_RawData_getRawData
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RawData
 * Method:    getLen
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_mousebird_maply_RawData_getLen
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RawData
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RawData_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_RawData
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RawData_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_RawData
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_RawData_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
