/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_VectorInfo */

#ifndef _Included_com_mousebird_maply_VectorInfo
#define _Included_com_mousebird_maply_VectorInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    setFilled
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_setFilled
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    setColor
 * Signature: (FFFF)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_setColor
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_VectorInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_VectorInfo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
