/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_GeometryInstance */

#ifndef _Included_com_mousebird_maply_GeometryInstance
#define _Included_com_mousebird_maply_GeometryInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setCenter
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setCenter
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setEndCenter
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setEndCenter
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setDuration
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setDuration
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setMatrix
 * Signature: (Lcom/mousebird/maply/Matrix4d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setMatrix
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setColor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setColor
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    setSelectable
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_setSelectable
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_GeometryInstance
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_GeometryInstance_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
