/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_WhirlyKitGLSetupInfo */

#ifndef _Included_com_mousebird_maply_WhirlyKitGLSetupInfo
#define _Included_com_mousebird_maply_WhirlyKitGLSetupInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_WhirlyKitGLSetupInfo
 * Method:    setMinZres
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_WhirlyKitGLSetupInfo_setMinZres
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_mousebird_maply_WhirlyKitGLSetupInfo
 * Method:    getMinZres
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_mousebird_maply_WhirlyKitGLSetupInfo_getMinZres
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_WhirlyKitGLSetupInfo
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_WhirlyKitGLSetupInfo_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_WhirlyKitGLSetupInfo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_WhirlyKitGLSetupInfo_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_WhirlyKitGLSetupInfo
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_WhirlyKitGLSetupInfo_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
