/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_CoordSystemDisplayAdapter */

#ifndef _Included_com_mousebird_maply_CoordSystemDisplayAdapter
#define _Included_com_mousebird_maply_CoordSystemDisplayAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    displayToLocal
 * Signature: (Lcom/mousebird/maply/Point3d;)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_displayToLocal
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    localToDisplay
 * Signature: (Lcom/mousebird/maply/Point3d;)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_localToDisplay
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    getBounds
 * Signature: (Lcom/mousebird/maply/Point3d;Lcom/mousebird/maply/Point3d;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_getBounds
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    screenPointFromGeoBatch
 * Signature: (Lcom/mousebird/maply/View;II[D[D[D[D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_screenPointFromGeoBatch
  (JNIEnv *, jobject, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    geoPointFromScreenBatch
 * Signature: (Lcom/mousebird/maply/View;II[D[D[D[D)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_geoPointFromScreenBatch
  (JNIEnv *, jobject, jobject, jint, jint, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    initialise
 * Signature: (Lcom/mousebird/maply/CoordSystem;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_initialise
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_CoordSystemDisplayAdapter
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_CoordSystemDisplayAdapter_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
