/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_OpenGLMemManager */

#ifndef _Included_com_mousebird_maply_OpenGLMemManager
#define _Included_com_mousebird_maply_OpenGLMemManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    getBufferID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLMemManager_getBufferID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    removeBufferID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_removeBufferID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    getTexID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_OpenGLMemManager_getTexID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    removeTexID
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_removeTexID
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    clearBufferIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_clearBufferIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    clearTextureIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_clearTextureIDs
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    dumpStats
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_dumpStats
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    lock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_lock
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    unlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_unlock
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_OpenGLMemManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_OpenGLMemManager_nativeInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
