/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_ParticleSystemAttribute_MaplyShaderAttrType */

#ifndef _Included_com_mousebird_maply_ParticleSystemAttribute_MaplyShaderAttrType
#define _Included_com_mousebird_maply_ParticleSystemAttribute_MaplyShaderAttrType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
