/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_QuadTrackerPointReturn */

#ifndef _Included_com_mousebird_maply_QuadTrackerPointReturn
#define _Included_com_mousebird_maply_QuadTrackerPointReturn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setScreenU
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setScreenU
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getScreenU
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getScreenU
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setScreenV
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setScreenV
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getScreenV
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getScreenV
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setMaplyTileID
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setMaplyTileID
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getMaplyTileID
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getMaplyTileID
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setPadding
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setPadding
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getPadding
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getPadding
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setLocX
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setLocX
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getLocX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getLocX
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setLocY
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setLocY
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getLocY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getLocY
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setTileU
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setTileU
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getTileU
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getTileU
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    setTileV
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_setTileV
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    getTileV
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_getTileV
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_QuadTrackerPointReturn
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_QuadTrackerPointReturn_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
