/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Point3d */

#ifndef _Included_com_mousebird_maply_Point3d
#define _Included_com_mousebird_maply_Point3d
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    getX
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Point3d_getX
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    getY
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Point3d_getY
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    getZ
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_com_mousebird_maply_Point3d_getZ
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    setValue
 * Signature: (DDD)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point3d_setValue
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    cross
 * Signature: (Lcom/mousebird/maply/Point3d;)Lcom/mousebird/maply/Point3d;
 */
JNIEXPORT jobject JNICALL Java_com_mousebird_maply_Point3d_cross
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point3d_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point3d_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_mousebird_maply_Point3d
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Point3d_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
