/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mousebird_maply_Scene */

#ifndef _Included_com_mousebird_maply_Scene
#define _Included_com_mousebird_maply_Scene
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mousebird_maply_Scene
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Scene_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mousebird_maply_Scene
 * Method:    addChangesNative
 * Signature: (Lcom/mousebird/maply/ChangeSet;)V
 */
JNIEXPORT void JNICALL Java_com_mousebird_maply_Scene_addChangesNative
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
